# Generated by Django 4.0.3 on 2022-04-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
