# Generated by Django 4.0.3 on 2022-04-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_profile_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='link',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default=None, upload_to='profiles'),
        ),
    ]
